### ISSUE TITLE
(false error code, no apps are working)

### ISSUE THREAD

**Issue by sonicfan888** [kawaiizenbo/AppManager#10]
Aware of duplicate of certain issue but this really needs attention. The game IS compatible with IPhone 3GS, i'm using 6.1.6
![bandicam 2024-01-11 19-53-07-960](https://github.com/kawaiizenbo/AppManager/assets/93792255/22a75a9f-49d7-460f-92a8-e82db82f1605)

Please explain what is the issue because no apps are working for me

**Comment by kawaiizenbo** [comment]
are you jailbroken with appsync installed?

**Comment by sonicfan888** [comment]
yeah i used p0sixspwn to jailbreak and i have appsync unified from karen's repo
(cydia was also updated from 1.1.9 to 1.1.30)

**Comment by sonicfan888** [comment]
late update but it works.
if anyone else has this problem just reinstall appsync unified and it should work, if not, reinstall it again
