### ISSUE TITLE
Could not connect to device, MissingHostId

### ISSUE THREAD

**Issue by ghost** [kawaiizenbo/AppManager#11]
I'm trying to connect it to my phone right now, but I keep running into this error. 
My iTunes version is 12.6.5
I'm on Windows 10
My iOS device is iPhone 12
I downloaded .NET frame 8
![Screenshot 2024-02-09 163425](https://github.com/kawaiizenbo/AppManager/assets/159585481/eb9bec7e-5d35-422a-8cd4-21227036f150)

**Comment by ghost** [comment]
Never mind, it was some iTunes issue. Completely reinstalling it fixed this.

**Comment by mbtools** [comment]
this happens if your device is still locked. Unlock it and select "Trust" on your device when prompted.
