### ISSUE TITLE
What does "ensure Apple Devices is not installed" mean?

### ISSUE THREAD

**Issue by eliluong** [kawaiizenbo/AppManager#14]
Hello, I currently have iTunes 12.6.5. The instructions for this application on the readme mention `ensure Apple Devices is not installed`. Can you please clarify what this means? iTunes was installed with default settings. Thank you.

**Comment by kawaiizenbo** [comment]
Apple Devices is one of three Microsoft store apps iTunes was recently split into. It causes driver conflicts with iTunes.
