### ISSUE TITLE
ERROR: install failed. Got error "IncorrectArchitecture" with code 0x00000000

### ISSUE THREAD

**Issue by EltafHalimi** [kawaiizenbo/AppManager#4]
Hello i wanted to install an ipa file on my  ipad with App Manager but then there comes that Error it says  failed to find matching arch for 64-bit Mach-o 
please help.

**Comment by kawaiizenbo** [comment]
if your ipad is on iPadOS 11 or newer you will not be able to install apps that do not have a 64 bit slice in the binary (generally made before 2013)

**Comment by EltafHalimi** [comment]
No I have a ipad 3,6 with ios 10.3.4 plus it's jailbroken

**Comment by EltafHalimi** [comment]
No I have an iPad 3,6 with ios 10.3.4 plus it's jailbroken

KawaiiZenbo ***@***.***> schrieb am Mo., 17. Okt. 2022, 23:25:
